aliados/urls.py
from django.urls import path
from aliados.views import ListarAliados, InsertarAliado, EditarAliado, BorrarAliado

urlpatterns=[
    path('aliados', ListarAliados.as_view(), name='aliados_list'),
    path('aliados/new', InsertarAliado.as_view(), name='insertar_aliado'),
    path('aliados/edit<int:pk>', EditarAliado.as_view(), name='editar_aliado'),
    path('aliados/delete<int:pk>', BorrarAliado.as_view(), name='borrar_aliado'),
]

appcap/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('aliados/',include(('aliados.urls','aliados'),namespace='aliados')),
    path('enemigos/',include(('enemigos.urls','enemigos'),namespace='enemigos')),
    path('patrocinadores/',include(('patrocinadores.urls','patrocinadores'),namespace='patrocinadores')),
    path('salvados/',include(('salvados.urls','salvados'),namespace='salvados')),
]

home/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import Home 
urlpatterns=[
    path('',Home.as_view(),name='home'),
]

aliados/models.py
from django.db import models

# Create your models here.
class Aliado(models.Model):
    nombre=models.CharField(
        max_length=100,
    )
    poder=models.CharField(
        max_length=100,
    )
    mundo=models.CharField(
        max_length=100,
    )
    def __str__(self):
        return '{}'.format(self.nombre)
    def save(self):
        super(Aliado, self).save()

    class Meta:
        verbose_name_plural="Aliados"

aliados/forms.py
from django import forms
from aliados.models import Aliado
class AliadoForm(forms.ModelForm):
    class Meta: 
        model=Aliado
        fields=['nombre','poder','mundo']
        labels={'Nombre':'Nombre del aliado','Poder': 'Poder del aliado','Mundo':'Mundo del aliado'}
        widget={'Nombre': forms.TextInput()}

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

aliados/views.py
from django.shortcuts import render
from aliados.models import Aliado
from django.views import generic
from aliados.forms import AliadoForm
from django.urls import reverse_lazy
# Create your views here.
class ListarAliados(generic.ListView):
    model=Aliado
    template_name="aliados/listar_aliados.html"
    context_object_name="obj"
class InsertarAliado(generic.CreateView):
    model=Aliado
    template_name="aliados/insertar_aliado.html"
    context_object_name="obj"
    form_class=AliadoForm
    success_url=reverse_lazy("aliados:aliados_list")
class EditarAliado(generic.UpdateView):
    model=Aliado
    template_name="aliados/insertar_aliado.html"
    context_object_name="obj"
    form_class=AliadoForm
    success_url=reverse_lazy("aliados:aliados_list")
class BorrarAliado(generic.DeleteView):
    model=Aliado
    template_name="aliados/borrar_aliado.html"
    context_object_name="obj"
    form_class=AliadoForm
    success_url=reverse_lazy("aliados:aliados_list")

aliados/templates/aliados/borrar_aliado.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            Eliminar Aliado
        </div>
        <div class ="panel-body">
            {% csrf_token %}
            <div class="alert alert-succes">
                Eliminar {{obj.nombre}}
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">Eliminar</span>
            </button>
            <a href="{% url 'aliados:aliados_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Regresar</a>
        </div>
    </div>
</div>
</form>
{% endblock contenido %}

aliados/templates/aliados/insertar_aliado.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel-body">
     
    {%csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-success">
        <span class="fa fa-save">
            Guardar Aliado
        </span>
    </button>
    <a href="{% url 'aliados:aliados_list' %}" class="btn btn-danger"><span class="fa fa-undo">Regresar a tus aliados</span></a>    
    </div>
</form>
{% endblock contenido %}

aliados/templates/aliados/listar_aliados.html
{% extends 'base/base.html' %}
{% block contenido %}
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>ID Aliado</th>
            <th>Nombre </th>
            <th>Poder</th>
            <th>Mundo</th>
            <th>Acciones con Aliados</th>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>
                {{item.id}}
            </td>
            <td>
                {{item.nombre}}
            </td>
            <td>
                {{item.poder}}
            </td>
            <td>
                {{item.mundo}}
            </td>
            <td>
            <a href="{% url 'aliados:editar_aliado' item.id %}" class="btn btn-primary btn-circle"><span class="fa fa-edit"></span>Editar Aliado</a> 
            <a href="{% url 'aliados:borrar_aliado' item.id %}" class="btn btn-danger btn-circle"><span class="fa fa-trash "></span>Eliminar Aliado</a> 
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock contenido %}