aliados/urls.py
from django.urls import path
from aliados.views import ListarAliados, InsertarAliado, EditarAliado, BorrarAliado

urlpatterns=[
    path('aliados', ListarAliados.as_view(), name='aliados_list'),
    path('aliados/new', InsertarAliado.as_view(), name='insertar_aliado'),
    path('aliados/edit<int:pk>', EditarAliado.as_view(), name='editar_aliado'),
    path('aliados/delete<int:pk>', BorrarAliado.as_view(), name='borrar_aliado'),
]

appcap/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('aliados/',include(('aliados.urls','aliados'),namespace='aliados')),
    path('enemigos/',include(('enemigos.urls','enemigos'),namespace='enemigos')),
    path('patrocinadores/',include(('patrocinadores.urls','patrocinadores'),namespace='patrocinadores')),
    path('salvados/',include(('salvados.urls','salvados'),namespace='salvados')),
]

enemigos/urls.py
from django.urls import path
from enemigos.views import ListarEnemigos, InsertarEnemigo, EditarEnemigo, BorrarEnemigo

urlpatterns=[
    path('enemigos', ListarEnemigos.as_view(), name='enemigos_list'),
    path('enemigos/new', InsertarEnemigo.as_view(), name='insertar_enemigo'),
    path('enemigos/edit<int:pk>', EditarEnemigo.as_view(), name='editar_enemigo'),
    path('enemigos/delete<int:pk>', BorrarEnemigo.as_view(), name='borrar_enemigo'),
]

home/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import Home 
urlpatterns=[
    path('',Home.as_view(),name='home'),
]

patrocinadores/urls.py
from django.urls import path
from patrocinadores.views import ListarPatrocinadores, InsertarPatrocinador, EditarPatrocinador, BorrarPatrocinador

urlpatterns =[
    path('patrocinadores', ListarPatrocinadores.as_view(), name='patrocinadores_list'),
    path('patrocinadores/new', InsertarPatrocinador.as_view(), name='insertar_patrocinador'),
    path('patrocinadores/edit<int:pk>', EditarPatrocinador.as_view(), name='editar_patrocinador'),
    path('patrocinadores/delete<int:pk>', BorrarPatrocinador.as_view(), name='borrar_patrocinador'),
]  

salvados/urls.py
from django.urls import path
from salvados.views import ListarSalvados, InsertarSalvado, EditarSalvado, BorrarSalvado

urlpatterns=[
    path('salvados', ListarSalvados.as_view(), name='salvados_list'),
    path('salvados/new', InsertarSalvado.as_view(), name='insertar_salvado'),
    path('salvados/edit<int:pk>', EditarSalvado.as_view(), name='editar_salvado'),
    path('salvados/delete<int:pk>', BorrarSalvado.as_view(), name='borrar_salvado'),

]

templates/base/base.html
<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <title> {% block head_title %}
    Capitan America
    {% endblock head_title %}
  </title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbars/">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="navbar.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
   
</head>

<body>


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

      <div class="collapse navbar-collapse" id="navbarsExample07">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home:home' %}">Inicio Americano<span class="sr-only">(current)</span></a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Aliados</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="{% url 'aliados:aliados_list' %}">Listar Aliados</a>
              <a class="dropdown-item" href="{% url 'aliados:insertar_aliado' %}">Insertar Aliados</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Enemigos</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="{% url 'enemigos:enemigos_list' %}">Listar Enemigos</a>
              <a class="dropdown-item" href="{% url 'enemigos:insertar_enemigo' %}">Insertar Enemigos</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Patrocinadores</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
            <a class="dropdown-item" href="{% url 'patrocinadores:patrocinadores_list' %}">Listar Patrocinadores</a>
            <a class="dropdown-item" href="{% url 'patrocinadores:insertar_patrocinador' %}">Insertar Patrocinador</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Personas Salvadas</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
            <a class="dropdown-item" href="{% url 'salvados:salvados_list' %}">Listar Personas Salvadas</a>
            <a class="dropdown-item" href="{% url 'salvados:insertar_salvado' %}">Insertar Persona Salvada</a>
            </div>
          </li>
        </ul>

      </div>
    </div>
  </nav>
  {% block contenido %}Se puede cambiar{% endblock contenido %}




  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
</body>


</html>