appcap/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('aliados/',include(('aliados.urls','aliados'),namespace='aliados')),
    path('enemigos/',include(('enemigos.urls','enemigos'),namespace='enemigos')),
    path('patrocinadores/',include(('patrocinadores.urls','patrocinadores'),namespace='patrocinadores')),
    path('salvados/',include(('salvados.urls','salvados'),namespace='salvados')),
]

home/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import Home 
urlpatterns=[
    path('',Home.as_view(),name='home'),
]

patrocinadores/urls.py
from django.urls import path
from patrocinadores.views import ListarPatrocinadores, InsertarPatrocinador, EditarPatrocinador, BorrarPatrocinador

urlpatterns =[
    path('patrocinadores', ListarPatrocinadores.as_view(), name='patrocinadores_list'),
    path('patrocinadores/new', InsertarPatrocinador.as_view(), name='insertar_patrocinador'),
    path('patrocinadores/edit<int:pk>', EditarPatrocinador.as_view(), name='editar_patrocinador'),
    path('patrocinadores/delete<int:pk>', BorrarPatrocinador.as_view(), name='borrar_patrocinador'),
]  

patrocinadores/models.py
from django.db import models

# Create your models here.
class Patrocinador(models.Model):
    nombre = models.CharField(
        max_length=100,
    )
    fondos =models.IntegerField()
    def __str__(self):
        return '{}'.format(self.nombre)

    def save(self):
        super(Patrocinador, self).save()
    
    class Meta:
        verbose_name_plural="Patrocinadores"

patrocinadores/forms.py
from django import forms
from patrocinadores.models import Patrocinador
class PatrocinadorForm(forms.ModelForm):
    class Meta: 
        model=Patrocinador
        fields=['nombre','fondos']
        labels={'Nombre':'Nombre del enemigo','Fondos':'Fondos'}
        widget={'Nombre': forms.TextInput()}

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

patrocinadores/views.py
from django.shortcuts import render
from patrocinadores.models import Patrocinador
from django.views import generic 
from patrocinadores.forms import PatrocinadorForm
from django.urls import reverse_lazy
# Create your views here.
class ListarPatrocinadores(generic.ListView):
    model=Patrocinador
    template_name="patrocinadores/listar_patrocinadores.html"
    context_object_name="obj"
class InsertarPatrocinador(generic.CreateView):
    model=Patrocinador
    template_name="patrocinadores/insertar_patrocinador.html"
    context_object_name="obj"
    form_class=PatrocinadorForm
    success_url=reverse_lazy("patrocinadores:patrocinadores_list")
class EditarPatrocinador(generic.UpdateView):
    model=Patrocinador
    template_name="patrocinadores/insertar_patrocinador.html"
    context_object_name="obj"
    form_class=PatrocinadorForm
    success_url=reverse_lazy("patrocinadores:patrocinadores_list")
class BorrarPatrocinador(generic.DeleteView):
    model=Patrocinador
    template_name="patrocinadores/borrar_patrocinador.html"
    context_object_name="obj"
    form_class=PatrocinadorForm
    success_url=reverse_lazy("patrocinadores:patrocinadores_list")
    

patrocinadores/templates/patrocinadores/borrar_patrocinador.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            Eliminar Patrocinador
        </div>
        <div class ="panel-body">
            {% csrf_token %}
            <div class="alert alert-succes">
                Eliminar {{obj.nombre}}
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">Eliminar</span>
            </button>
            <a href="{% url 'patrocinadores:patrocinadores_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Regresar a Patrocinador</a>
        </div>
    </div>
</div>
</form>
{% endblock contenido %}

patrocinadores/templates/patrocinadores/insertar_patrocinador.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel-body">
     
    {%csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-success">
        <span class="fa fa-save">
            Guardar Patrocinador
        </span>
    </button>
    <a href="{% url 'patrocinadores:patrocinadores_list' %}" class="btn btn-danger"><span class="fa fa-undo">Regresar a patrocinadores</span></a>    
    </div>
</form>
{% endblock contenido %}

patrocinadores/templates/patrocinadores/listar_patrocinadores.html
{% extends 'base/base.html' %}
{% block contenido %}
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>ID Patrocinador</th>
            <th>Nombre</th>
            <th>Fondos</th>
            <th>Acciones Con Patrocinadores</th>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>
                {{item.id}}
            </td>
            <td>
                {{item.nombre}}
            </td>
            <td>
                {{item.fondos}}
            </td>
            <td>
                <a href="{% url 'patrocinadores:editar_patrocinador' item.id %}" class="btn btn-primary btn-circle"><span class="fa fa-edit"></span>Editar Patrocinador</a>
                <a href="{% url 'patrocinadores:borrar_patrocinador' item.id %}" class="btn btn-danger btn-circle"><span class="fa fa-trash"></span>Eliminar Patrocinador</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock contenido %}