appcap/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('aliados/',include(('aliados.urls','aliados'),namespace='aliados')),
    path('enemigos/',include(('enemigos.urls','enemigos'),namespace='enemigos')),
    path('patrocinadores/',include(('patrocinadores.urls','patrocinadores'),namespace='patrocinadores')),
    path('salvados/',include(('salvados.urls','salvados'),namespace='salvados')),
]

home/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import Home 
urlpatterns=[
    path('',Home.as_view(),name='home'),
]

salvados/urls.py
from django.urls import path
from salvados.views import ListarSalvados, InsertarSalvado, EditarSalvado, BorrarSalvado

urlpatterns=[
    path('salvados', ListarSalvados.as_view(), name='salvados_list'),
    path('salvados/new', InsertarSalvado.as_view(), name='insertar_salvado'),
    path('salvados/edit<int:pk>', EditarSalvado.as_view(), name='editar_salvado'),
    path('salvados/delete<int:pk>', BorrarSalvado.as_view(), name='borrar_salvado'),

]

salvados/models.py
from django.db import models

# Create your models here.
class Salvado(models.Model):
    nombre=models.CharField(
        max_length=100,
    )
    nacionalidad=models.CharField(
        max_length=100,
    )
    edad=models.CharField(
        max_length=100,
    )
    def __str__(self):
        return '{}'.format(self.nombre)
    def save(self):
        super(Salvado, self).save()

    class Meta:
        verbose_name_plural="Salvados"

salvados/forms.py
from django import forms
from salvados.models import Salvado
class SalvadoForm(forms.ModelForm):
    class Meta: 
        model=Salvado
        fields=['nombre','nacionalidad','edad']
        labels={'Nombre':'Nombre del enemigo','Nacionalidad':'Nacionalidad','edad':'edad'}
        widget={'Nombre': forms.TextInput()}

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

salvados/views.py
from django.shortcuts import render
from salvados.models import Salvado
from django.views import generic
from salvados.forms import SalvadoForm
from django.urls import reverse_lazy

class ListarSalvados(generic.ListView):
    model=Salvado
    template_name="salvados/listar_salvados.html"
    context_object_name="obj"
class InsertarSalvado(generic.CreateView):
    model=Salvado
    template_name="salvados/insertar_salvado.html"
    context_object_name="obj"
    form_class=SalvadoForm
    success_url=reverse_lazy("salvados:salvados_list")
class EditarSalvado(generic.UpdateView):
    model=Salvado
    template_name="salvados/insertar_salvado.html"
    context_object_name="obj"
    form_class=SalvadoForm
    success_url=reverse_lazy("salvados:salvados_list")
class BorrarSalvado(generic.DeleteView):
    model=Salvado
    template_name="salvados/borrar_salvado.html"
    context_object_name="obj"
    form_class=SalvadoForm
    success_url=reverse_lazy("salvados:salvados_list")

salvados/templates/salvados/borrar_salvado.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel panel-default">
        <div class="panel-heading">
            Eliminar Persona Salvada
        </div>
        <div class ="panel-body">
            {% csrf_token %}
            <div class="alert alert-succes">
                Eliminar {{obj.nombre}}
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">Eliminar</span>
            </button>
            <a href="{% url 'salvados:salvados_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Regresar a Salvados</a>
        </div>
    </div>
</div>
</form>
{% endblock contenido %}

salvados/templates/salvados/insertar_salvado.html
{% extends 'base/base.html' %}
{% block contenido %}
<form method="post">
    <div class="panel-body">
     
    {%csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-success">
        <span class="fa fa-save">
            Guardar Persona Salvada
        </span>
    </button>
    <a href="{% url 'salvados:salvados_list' %}" class="btn btn-danger"><span class="fa fa-undo">Regresar a Salvados</span></a>    
    </div>
</form>
{% endblock contenido %}

salvados/templates/salvados/listar_salvados.html
{% extends 'base/base.html' %}
{% block contenido %}
<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Nacionalidad</th>
            <th>Edad</th>
            <th>Acciones Con Personas Salvadas</th>
        </tr>
    </thead>
    <tbody>
        {% for item in obj %}
        <tr>
            <td>
                {{item.id}}
            </td>
            <td>
                {{item.nombre}}
            </td>
            <td>
                {{item.nacionalidad}}
            </td>
            <td>
                {{item.edad}}
            </td>
            <td>
             <a href="{% url 'salvados:editar_salvado' item.id %}" class ="btn btn-primary btn-circle"><span class="fa fa-edit"></span>Editar Salvado</a>
             <a href="{% url 'salvados:borrar_salvado' item.id %}" class ="btn btn-danger btn-circle"><span class="fa fa-trash"></span>Eliminar Salvado</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock contenido %}